site_name: HPE OneView PowerShell Module Documentation
site_author: ChrisLynchHPE
repo_name: HewlettPackard/POSH-HPEOneView-docs
repo_url: https://hewlettpackard.github.io/posh-hpeoneview-docs
site_url: https://hewlettpackard.github.io
edit_uri: edit/main/docs

copyright: >
  Copyright &copy; 2013-2025 Hewlett Packard Enterprise Development LP
  <a href="#__consent">Change cookie settings</a>
  <a href="https://www.hpe.com/us/en/legal/privacy.html">Hewlett Packard Enterprise privacy statement.</a>

theme:
  name: material
  # logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  primary: custom

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
    

extra:
  copyright: Copyright &copy; 2013-2025 Hewlett Packard Enterprise Development LP
  version:
    provider: mike
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/HewlettPackard/POSH-HPEOneView/issues/new/?title=[DocsFeedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.

  plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      redirect_template: null
      deploy_prefix: 'v{version}'
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

  consent:
    cookies:
      analytics:
        name: Google Analytics
        checked: false